### ISSUE TITLE
Don't automatically show plots

### ISSUE THREAD

**Issue by aj-foster** [exosports/BART#11]
Reasoning:

1. If, by chance, you run the code in an SSH session rather than a VNC session, everything crashes at the end of the run because python can't connect to a display. This is liable to make someone very unhappy if they are trying out the code for the first time.
2. This code runs for a long time. The chances that someone will be sitting and watching it when execution ends are very small. Opening plots automatically adds little value to the user.
3. I have a natural aversion to things popping up unexpectedly.

**Comment by aj-foster** [comment]
@AndrewSDFoster is this still an issue?

**Comment by AndrewSDFoster** [comment]
Nope, I fixed it in a pull request to MCcubed a while back.

**Comment by aj-foster** [comment]
Excellent.
