### ISSUE TITLE
BART crashes if argument 'outflux' is not given, with no clear warnings.

### ISSUE THREAD

**Issue by rychallener** [exosports/BART#32]
It may be intended that BART does not work without 'outflux', but if so we need to make it obvious to the user that this is the problem.

**Comment by pcubillos** [comment]
I agree, we should add an explicit warning

**Comment by pcubillos** [comment]
On topic:
@dzesmin @rychallener 
Having to switch between ``outflux`` and ``outmod`` in the config file gets annoying too.
What about having a single name for the main output? ``outspec``??

**Comment by rychallener** [comment]
I like that idea. We already specify the solution type so it's redundant to require a different output option for each case.

**Comment by pcubillos** [comment]
Ok, I'll take care of this.
