### ISSUE TITLE
repo contains symlinks to directories not contained in repo

### ISSUE THREAD

**Issue by natelust** [exosports/BART#7]
Files in the directory BART/modules/commloop/src/mpi refer to symlinks on development system in the directory /usr/share/pyshared/mpi4py/include/mpi4py/ . This is outside the development repo, and is not cloned into repositories on a pull. These files may or may not be relevant to the functioning of the software. If they are they should be included otherwise users not on the development computer (exo) will not be able to properly use the software.

**Comment by aj-foster** [comment]
Given that commloop has been taken out, I'm going to assume that this is no longer an issue. Feel free to reopen if that isn't the case.
